# +----------------------------------------------------------------+
# | Makefile for MathTL documentation                              |
# |                                                                |
# | Copyright (c) 2004                                             |
# | Thorsten Raasch                                                |
# +----------------------------------------------------------------+

all:: pdf

pdf::	
	pdflatex MathTL.tex
	pdflatex MathTL.tex

clean::
	rm -f *.aux *~ *.log *.dvi *.pdf
