
all:: examples

examples::
	cd Example_PlotCoefficients; $(MAKE)
	cd Example_CDD1; $(MAKE)
	cd Example_CDD2; $(MAKE)

clean::
	cd Example_PlotCoefficients; $(MAKE) clean
	cd Example_CDD1; $(MAKE) clean
	cd Example_CDD2; $(MAKE) clean

